---
title: "accounts_analysis"
output: html_document
---

Get basic infomation of all accounts
```{r}
## accounts summary
### read accounts
accounts <- readRDS(paste0(data, "/accounts.Rds"))
### lookup all basic data
accounts_summary <- lookup_users(accounts)
## columns names of columns with with NA values
columns_with_na <- names(select(accounts_summary, contains("_count")))
## reemplace columns with NA values with 0
accounts_summary[columns_with_na][is.na(accounts_summary[columns_with_na])] <- 0
## clean variables
rm(columns_with_na)
```

Select only relevant columns
```{r}
accounts_summary_df <- accounts_summary %>%
        select(user_id, screen_name, name, location, description, followers_count, friends_count, statuses_count, account_created_at)
```

Add type
```{r}
accounts_summary_df$type <- NA
accounts_summary_df$type[accounts_summary_df$screen_name %in% congress_peru] <- "Congress"
accounts_summary_df$type[accounts_summary_df$screen_name %in% journalists] <- "Journalists"
accounts_summary_df$type[accounts_summary_df$screen_name %in% politicians] <- "Politicians"
accounts_summary_df$type[accounts_summary_df$screen_name %in% government] <- "Government"
accounts_summary_df$type[accounts_summary_df$screen_name %in% blogs] <- "Blogs"
accounts_summary_df$type[accounts_summary_df$screen_name %in% media] <- "Media"
accounts_summary_df$type[accounts_summary_df$screen_name %in% interest_groups] <-"Interest Groups"
```

Write and read csv table
```{r}
saveRDS(accounts_summary_df, file = paste0(data, "/accounts_summary.Rds"))
### save as csv for easy reading
write_csv(accounts_summary_df, paste0(data, "/accounts_summary.csv"))
```


